### PR TITLE
Modifiable "Eye of Ender"

### PR DESCRIPTION
**Pull request by maksim789456**
Hi! I noticed that "Eye of Ender" cannot be edited and I implemented edit.
Also PR closes issue #75

Didn't find a better icon of "Eye of Ender" and with absence game packs maybe looks different from others icons :)
Bellow some screenshots of the changes

Without game paks:
MCDSaveEdit_6PhPSr1Wg5
MCDSaveEdit_9TH1FCc9Rz

With game paks:
MCDSaveEdit_MnSCyHR5ly
MCDSaveEdit_xrJkGUg3N3

### CODE REVIEW

**Comment by axel7083** [comment]
Changing this value is not enough to unlock the end portal.
I would recommend to create a `unlock portal` button which change those values in the strongholdProgress field :
- strongholdDeepwoodBrookUnlocked
- strongholdHighblockHideawayUnlocked
- strongholdOldTownHallUnlocked
- strongholdSunkenWatchtowerUnlocked
- strongholdTheTrialOfTheNamelessUnlocked
- strongholdTheUndercroftUnlocked

I don't know exactly how the property EyeOfEnder is used, but if those boolean are not set to true, I was not able to put the enderpeal in the portal.

**Comment by maksim789456** [comment]
> Changing this value is not enough to unlock the end portal. I would recommend to create a `unlock portal` button which change those values in the strongholdProgress field :

Indeed, without these fields to true, the game does not allow put your eyes of ender in the portal

I implemented "Unlock Portal" button. She sets these fields to true values
The button is displayed if save loaded and at least one "stronghold*Unlocked" field is set to false
MCDSaveEdit_2s0K33tmNF

**Comment by FHRayS** [comment]
I've tried another one trainer, there's an 'unlimited emerald' option, it set the number of eyes of ender to 9999999, now i just want set it to 0, will it be available in the next update?

**Comment by maksim789456** [comment]
> I've tried another one trainer, there's an 'unlimited emerald' option, it set the number of eyes of ender to 9999999, now i just want set it to 0, will it be available in the next update?

I think If @CutFlame will accept PR then the functionality will appear in the new release 😄

**Pull request merged**
